version: '3'
services:
  nginx:
   container_name: nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
 
  db:
   image: postgres:10.4
   environment:
     POSTGRES_PASSWORD: amawta
     POSTGRES_USER: amawta
     POSTGRES_DB: amawta
   ports:
   - "5432:5432"
   volumes:
      - ./postgres-data:/var/lib/postgresql/data
   restart: always
  
  app:
    container_name: amawta-backend
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
      - db
    restart: always
